# Generated by Django 6.1 on 2026-08-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Wpływ'), ('EXPENSE', 'Wydatek')], max_length=20),
        ),
    ]
